export const CATEGORIES = ["Todos", "Rulos", "Paradiddles", "Flams", "Drags"];

export const SUBDIVISIONS = [
  { val: 2, label: "8ªs" },
  { val: 3, label: "Tercinas" },
  { val: 4, label: "16ªs" },
  { val: 6, label: "Sextinas" },
];

export const RUDIMENTS = [
  // ==========================================
  // RULOS (1 a 15)
  // ==========================================
  {
    id: "1",
    name: "Single Stroke Roll",
    sticking: ["R", "L", "R", "L", "R", "L", "R", "L"],
    cat: "Rulos",
    sub: 4,
    time: "2/4",
  },
  {
    id: "2",
    name: "Single Stroke Four",
    sticking: ["R", "L", "R", "L", "-"],
    cat: "Rulos",
    sub: 4,
    time: "2/4",
    dur: [1, 1, 1, 1, 4],
  },
  {
    id: "3",
    name: "Single Stroke Seven",
    sticking: ["R", "L", "R", "L", "R", "L", "R", "-"],
    cat: "Rulos",
    sub: 6,
    time: "2/4",
    dur: [1, 1, 1, 1, 1, 1, 3, 3],
  },
  {
    id: "4",
    name: "Multiple Bounce Roll",
    sticking: ["R", "L", "R", "L", "R", "L", "R", "L"],
    cat: "Rulos",
    sub: 4,
    time: "2/4",
  },
  {
    id: "5",
    name: "Triple Stroke Roll",
    sticking: ["R", "R", "R", "L", "L", "L"],
    cat: "Rulos",
    sub: 3,
    time: "2/4",
  },
  {
    id: "6",
    name: "Double Stroke Roll",
    sticking: ["R", "R", "L", "L", "R", "R", "L", "L"],
    cat: "Rulos",
    sub: 4,
    time: "2/4",
  },
  {
    id: "7",
    name: "Five Stroke Roll",
    sticking: ["R", "R", "L", "L", "R", "-"],
    cat: "Rulos",
    sub: 4,
    time: "2/4",
    dur: [1, 1, 1, 1, 2, 2],
  },
  {
    id: "8",
    name: "Six Stroke Roll",
    sticking: ["R", "L", "L", "R", "R", "L"],
    cat: "Rulos",
    sub: 6,
    time: "2/4",
    dur: [2, 1, 1, 1, 1, 6],
  },
  {
    id: "9",
    name: "Seven Stroke Roll",
    sticking: ["R", "R", "L", "L", "R", "R", "L", "-"],
    cat: "Rulos",
    sub: 4,
    time: "2/4",
    dur: [1, 1, 1, 1, 1, 1, 2, 8],
  },
  {
    id: "10",
    name: "Nine Stroke Roll",
    sticking: ["R", "R", "L", "L", "R", "R", "L", "L", "R", "-"],
    cat: "Rulos",
    sub: 4,
    time: "4/4",
    dur: [1, 1, 1, 1, 1, 1, 1, 1, 4, 4],
  },
  {
    id: "11",
    name: "Ten Stroke Roll",
    sticking: ["R", "R", "L", "L", "R", "R", "L", "L", "R", "L", "-"],
    cat: "Rulos",
    sub: 4,
    time: "4/4",
    dur: [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 4],
  },
  {
    id: "12",
    name: "Eleven Stroke Roll",
    sticking: ["R", "R", "L", "L", "R", "R", "L", "L", "R", "R", "L", "-"],
    cat: "Rulos",
    sub: 6,
    time: "2/4",
    dur: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 12],
  },
  {
    id: "13",
    name: "Thirteen Stroke Roll",
    sticking: [
      "R",
      "R",
      "L",
      "L",
      "R",
      "R",
      "L",
      "L",
      "R",
      "R",
      "L",
      "L",
      "R",
      "-",
    ],
    cat: "Rulos",
    sub: 6,
    time: "4/4",
    dur: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 6],
  },
  {
    id: "14",
    name: "Fifteen Stroke Roll",
    sticking: [
      "R",
      "R",
      "L",
      "L",
      "R",
      "R",
      "L",
      "L",
      "R",
      "R",
      "L",
      "L",
      "R",
      "R",
      "L",
      "-",
    ],
    cat: "Rulos",
    sub: 4,
    time: "4/4",
    dur: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 16],
  },
  {
    id: "15",
    name: "Seventeen Stroke Roll",
    sticking: [
      "R",
      "R",
      "L",
      "L",
      "R",
      "R",
      "L",
      "L",
      "R",
      "R",
      "L",
      "L",
      "R",
      "R",
      "L",
      "L",
      "R",
      "-",
    ],
    cat: "Rulos",
    sub: 4,
    time: "4/4",
    dur: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 8],
  },

  // ==========================================
  // PARADIDDLES (16 a 19)
  // ==========================================
  {
    id: "16",
    name: "Single Paradiddle",
    sticking: ["R", "L", "R", "R", "L", "R", "L", "L"],
    cat: "Paradiddles",
    sub: 4,
    time: "2/4",
  },
  {
    id: "17",
    name: "Double Paradiddle",
    sticking: ["R", "L", "R", "L", "R", "R", "L", "R", "L", "R", "L", "L"],
    cat: "Paradiddles",
    sub: 6,
    time: "2/4",
  },
  {
    id: "18",
    name: "Triple Paradiddle",
    sticking: [
      "R",
      "L",
      "R",
      "L",
      "R",
      "L",
      "R",
      "R",
      "L",
      "R",
      "L",
      "R",
      "L",
      "R",
      "L",
      "L",
    ],
    cat: "Paradiddles",
    sub: 4,
    time: "4/4",
  },
  {
    id: "19",
    name: "Single Paradiddle-Diddle",
    sticking: ["R", "L", "R", "R", "L", "L", "L", "R", "L", "L", "R", "R"],
    cat: "Paradiddles",
    sub: 6,
    time: "2/4",
  },

  // ==========================================
  // FLAMS (20 a 30)
  // ==========================================
  {
    id: "20",
    name: "Flam",
    sticking: ["lR", "rL"],
    cat: "Flams",
    sub: 2,
    time: "2/4",
  },
  {
    id: "21",
    name: "Flam Accent",
    sticking: ["lR", "L", "R", "rL", "R", "L"],
    cat: "Flams",
    sub: 3,
    time: "2/4",
  },
  {
    id: "22",
    name: "Flam Tap",
    sticking: ["lR", "R", "rL", "L"],
    cat: "Flams",
    sub: 2,
    time: "2/4",
  },
  {
    id: "23",
    name: "Flamacue",
    sticking: ["lR", "L", "R", "L", "lR", "rL", "R", "L", "R", "rL"],
    cat: "Flams",
    sub: 4,
    time: "5/4",
    dur: [1, 1, 1, 1, 4, 1, 1, 1, 1, 4],
  },
  {
    id: "24",
    name: "Flam Paradiddle",
    sticking: ["lR", "L", "R", "R", "rL", "R", "L", "L"],
    cat: "Flams",
    sub: 4,
    time: "2/4",
  },
  {
    id: "25",
    name: "Single Flammed Mill",
    sticking: ["lR", "R", "L", "R", "rL", "L", "R", "L"],
    cat: "Flams",
    sub: 4,
    time: "2/4",
  },
  {
    id: "26",
    name: "Flam Paradiddle-Diddle",
    sticking: ["lR", "L", "R", "R", "L", "L", "rL", "R", "L", "L", "R", "R"],
    cat: "Flams",
    sub: 6,
    time: "2/4",
  },
  {
    id: "27",
    name: "Pataflafla",
    sticking: ["lR", "R", "L", "rL", "rL", "L", "R", "lR"],
    cat: "Flams",
    sub: 4,
    time: "2/4",
  },
  {
    id: "28",
    name: "Swiss Army Triplet",
    sticking: ["lR", "R", "L", "rL", "L", "R"],
    cat: "Flams",
    sub: 3,
    time: "2/4",
  },
  {
    id: "29",
    name: "Inverted Flam Tap",
    sticking: ["lR", "L", "rL", "R"],
    cat: "Flams",
    sub: 2,
    time: "2/4",
  },
  {
    id: "30",
    name: "Flam Drag",
    sticking: ["lR", "llR", "L", "rL", "rrL", "R"],
    cat: "Flams",
    sub: 3,
    time: "2/4",
  },

  // ==========================================
  // DRAGS (31 a 40)
  // ==========================================
  {
    id: "31",
    name: "Drag",
    sticking: ["llR", "rrL"],
    cat: "Drags",
    sub: 2,
    time: "2/4",
  },
  {
    id: "32",
    name: "Single Drag Tap",
    sticking: ["llR", "L", "rrL", "R"],
    cat: "Drags",
    sub: 2,
    time: "2/4",
  },
  {
    id: "33",
    name: "Double Drag Tap",
    sticking: ["llR", "llR", "L", "rrL", "rrL", "R"],
    cat: "Drags",
    sub: 4,
    time: "4/4",
    dur: [2, 2, 4, 2, 2, 4],
  },
  {
    id: "34",
    name: "Lesson 25",
    sticking: ["llR", "L", "R", "rrL", "R", "L"],
    cat: "Drags",
    sub: 4,
    time: "2/4",
    dur: [1, 1, 2, 1, 1, 2],
  },
  {
    id: "35",
    name: "Single Dragadiddle",
    sticking: ["llR", "L", "R", "R", "rrL", "R", "L", "L"],
    cat: "Drags",
    sub: 4,
    time: "2/4",
  },
  {
    id: "36",
    name: "Drag Paradiddle #1",
    sticking: ["R", "llR", "L", "R", "R", "L", "rrL", "R", "L", "L"],
    cat: "Drags",
    sub: 4,
    time: "4/4",
    dur: [2, 1, 1, 2, 2, 2, 1, 1, 2, 2],
  },
  {
    id: "37",
    name: "Drag Paradiddle #2",
    sticking: [
      "R",
      "llR",
      "llR",
      "L",
      "R",
      "R",
      "L",
      "rrL",
      "rrL",
      "R",
      "L",
      "L",
    ],
    cat: "Drags",
    sub: 4,
    time: "6/4",
    dur: [2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2],
  },
  {
    id: "38",
    name: "Single Ratamacue",
    sticking: ["llR", "L", "R", "L", "rrL", "R", "L", "R"],
    cat: "Drags",
    sub: 4,
    time: "2/4",
    dur: [1, 1, 2, 4, 1, 1, 2, 4],
  },
  {
    id: "39",
    name: "Double Ratamacue",
    sticking: ["llR", "llR", "L", "R", "L", "rrL", "rrL", "R", "L", "R"],
    cat: "Drags",
    sub: 4,
    time: "3/4",
    dur: [2, 2, 1, 1, 6, 2, 2, 1, 1, 6],
  },
  {
    id: "40",
    name: "Triple Ratamacue",
    sticking: [
      "llR",
      "llR",
      "llR",
      "L",
      "R",
      "L",
      "rrL",
      "rrL",
      "rrL",
      "R",
      "L",
      "R",
    ],
    cat: "Drags",
    sub: 4,
    time: "4/4",
    dur: [2, 2, 2, 1, 1, 8, 2, 2, 2, 1, 1, 8],
  },
];
